export const ERROR_CODES = {
  BOOL_VALUE_INVALID: "BOOL_VALUE_INVALID",
  DEPTH_LIMIT_EXCEEDED: "DEPTH_LIMIT_EXCEEDED",
  DUPLICATE_TYPE_ID: "DUPLICATE_TYPE_ID",
  FRAME_TOO_LARGE: "FRAME_TOO_LARGE",
  INVALID_FIELD_VALUE: "INVALID_FIELD_VALUE",
  INVALID_NODE_TYPE: "INVALID_NODE_TYPE",
  INVALID_SHAPE: "INVALID_SHAPE",
  LENGTH_MISMATCH: "LENGTH_MISMATCH",
  NEED_MORE_DATA: "NEED_MORE_DATA",
  OUT_OF_BOUNDS: "OUT_OF_BOUNDS",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  UNKNOWN_TYPE_ID: "UNKNOWN_TYPE_ID",
  UTF8_INVALID: "UTF8_INVALID"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
