export const ERROR_CODES = {
  ARRAY_LENGTH_EXCEEDED: "ARRAY_LENGTH_EXCEEDED",
  BOOL_VALUE_INVALID: "BOOL_VALUE_INVALID",
  BUFFER_LIMIT_EXCEEDED: "BUFFER_LIMIT_EXCEEDED",
  DEPTH_LIMIT_EXCEEDED: "DEPTH_LIMIT_EXCEEDED",
  DUPLICATE_TYPE_ID: "DUPLICATE_TYPE_ID",
  FRAME_TOO_LARGE: "FRAME_TOO_LARGE",
  HEADER_CHECKSUM_MISMATCH: "HEADER_CHECKSUM_MISMATCH",
  INVALID_FIELD_VALUE: "INVALID_FIELD_VALUE",
  INVALID_FRAME_FLAGS: "INVALID_FRAME_FLAGS",
  INVALID_FRAME_MAGIC: "INVALID_FRAME_MAGIC",
  INVALID_NODE_TYPE: "INVALID_NODE_TYPE",
  INVALID_SHAPE: "INVALID_SHAPE",
  INVALID_TYPE_ID: "INVALID_TYPE_ID",
  LENGTH_MISMATCH: "LENGTH_MISMATCH",
  NEED_MORE_DATA: "NEED_MORE_DATA",
  OUT_OF_BOUNDS: "OUT_OF_BOUNDS",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  PAYLOAD_CHECKSUM_MISMATCH: "PAYLOAD_CHECKSUM_MISMATCH",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  STRING_LENGTH_EXCEEDED: "STRING_LENGTH_EXCEEDED",
  UNKNOWN_TYPE_ID: "UNKNOWN_TYPE_ID",
  UNKNOWN_FIELD: "UNKNOWN_FIELD",
  UNKNOWN_PAYLOAD_KIND: "UNKNOWN_PAYLOAD_KIND",
  UNSUPPORTED_FRAME_VERSION: "UNSUPPORTED_FRAME_VERSION",
  UTF8_INVALID: "UTF8_INVALID"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
